name: Dart CI and Release

on:
  push:
    branches: [master]
    tags: ['v*']
  pull_request:
    branches: [master]

permissions:
  contents: write # Необходимо для создания релизов

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [Ubuntu-latest, macos-latest, windows-latest]
        sdk: [3.7.2, stable, beta]
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Install dependencies
        run: dart pub get
      - name: Run tests
        run: dart test

  release:
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [Ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Install dependencies
        run: dart pub get
      - name: Compile executable
        run: |
          mkdir output
          dart compile exe bin/manpass.dart -o output/manpass${{ matrix.os == 'windows-latest' && '.exe' || '' }}
      - name: Debug output directory
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            dir output/
          else
            ls -la output/
          fi
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.os }}
          path: output/
