name: Dart CI and Release

on:
  push:
    branches: [master]
    tags: ['v*'] # Триггер для тегов вида v1.0.0
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: [3.7.2, stable, beta]
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: dart test

  release:
    needs: test # Запускается только после успешного выполнения тестов
    if: startsWith(github.ref, 'refs/tags/v') # Запускается только для тегов
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Compile executable
        run: |
          mkdir output
          dart compile exe bin/manpass.dart -o output/manpass${{ matrix.os == 'windows-latest' && '.exe' || '' }}
        # Предполагается, что ваш CLI находится в bin/main.dart

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.os }}
          path: output/

  publish-release:
    needs: release
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binary-ubuntu-latest
          path: binaries/linux/
      - uses: actions/download-artifact@v4
        with:
          name: binary-macos-latest
          path: binaries/macos/
      - uses: actions/download-artifact@v4
        with:
          name: binary-windows-latest
          path: binaries/windows/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            binaries/linux/*
            binaries/macos/*
            binaries/windows/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
